# Generated by Django 4.0.5 on 2022-07-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project2_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project2',
            name='description',
            field=models.TextField(),
        ),
    ]
