# Generated by Django 4.0.5 on 2022-07-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link_name',
        ),
    ]
